### ISSUE TITLE
Merging 2 Different Types of Roads Smoothly

### ISSUE THREAD

**Issue by shadertheboi** [kianzarrin/DirectConnectRoads#2]
![Screenshot 2021-06-05 192725](https://user-images.githubusercontent.com/59530097/120890267-15b95a80-c634-11eb-8f74-626ab861bcc3.jpg)

As shown in the screenshot, 2 segments running parallel along with one another through a node do not blend in smoothly.

I thought using the Node Controller might do the trick, but unfortunately to no avail. 

Trying with Intersection Marking Tool now...

![Screenshot 2021-06-05 201213](https://user-images.githubusercontent.com/59530097/120891304-692ea700-c63a-11eb-89c1-dfac7a70170d.jpg)

Actually, it's quite doable with the mod albeit not perfect.

**Comment by kianzarrin** [comment]
can this be done with stretch node? The lane markers won't look like that though.
if you want to sort out the lane markers the only option is Intersection markup tool
https://steamcommunity.com/sharedfiles/filedetails/?id=2140418403

**Comment by kianzarrin** [comment]
oh wait I didn't notice the side road. in that cause NC cannot do that.
you should do this with IMT.
in future I might provide something for median/tracks in AR.

**Comment by shadertheboi** [comment]
Yup, IMT seems to be the stopper plug for now. I'm confident you would be able to figure something out on your side.

**Comment by kianzarrin** [comment]
AN is supposed to this now.
